config/routes.rb
Rails.application.routes.draw do
  resources 'settings'
  resources 'checkouts'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :cards
end

app/controllers/application_controller.rb
require 'square_connect'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def load_config
    return @config if @config
    @config = YAML.load_file(Rails.root.join('config', 'square.yml'))[Rails.env]
    return @config
  end
  
  def square
    return @square if @square
    @square = SquareConnect.configure do |config|
      config.access_token = load_config['access_token']
    end
    @square
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :square, only: [:create]
  
  def index
  end
  
  def create
    idempotency_key = SecureRandom.uuid
    card = current_user.cards.find(params[:checkout][:card])
    amount = params[:checkout][:amount].to_i
    
    api = SquareConnect::TransactionsApi.new
    transaction = api.charge(load_config['location_id'], {
      idempotency_key: idempotency_key,
      amount_money: {
        amount: amount, currency: 'JPY'
      },
      customer_id: current_user.square_customer_id,
      customer_card_id: card.nonce
    }).to_hash[:transaction]
    redirect_to checkout_path(transaction[:id])
  end
  
  def show
    @transaction_id = params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :square, only: [:create]
  
  def index
    @cards = current_user.cards.all
  end

  def show
  end
  
  def create
    card_nonce = params[:nonce]
    api = SquareConnect::CustomersApi.new
    
    if current_user.square_customer_id.nil?
      customer = api.create_customer({
        email_address: current_user.email
      }).to_hash[:customer]
      current_user.update_attribute :square_customer_id, customer[:id]
    end
    
    card = api.create_customer_card(
      current_user.square_customer_id, {
      card_nonce: card_nonce
    }).to_hash[:card]
    
    current_user.cards.create(
      nonce: card[:id],
      last4: params[:last_4],
      brand: params[:card_brand],
      exp_month: params[:exp_month],
      exp_year: params[:exp_year]
    )
    redirect_to settings_path
  end
  
  def destroy
    card = current_user.cards.find(params[:id])
    card.destroy if card
    redirect_to settings_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
  def load_config
    return @config if @config
    @config = YAML.load_file(Rails.root.join('config', 'square.yml'))[Rails.env]
    return @config
  end
end

app/views/checkouts/index.html.erb
<h2>支払いを行う</h2>
<%= form_for checkouts_path, method: 'post' do |f| %>
  <div class="form-group">
    <label for="inputCardNumber">カードを選択</label>
    <%= select :checkout, :card, current_user.cards.map {|card| ["#{card.brand} - 下四桁 #{card.last4}", card.id]}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="inputCardNumber">支払額</label>
    <div class="row">
      <div class="col-md-3">
        <%= text_field :checkout, :amount, class: 'form-control', value: 1000 %>
      </div>
      <div class="col-md-1">
        円
      </div>
    </div>
  </div>
  
  <button class="btn btn-default">
    支払う
  </button>
<% end %>

app/views/checkouts/show.html.erb
<h2>決済が完了しました</h2>
<p>
  お支払いが完了しました。この決済に関するお問い合わせは <%= @transaction_id %> をお使いください。
</p>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <p><%= link_to "支払い方法追加", settings_path %></p>
  <p><%= link_to "支払いを行う", checkouts_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.squareup.com/v2/paymentform' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Square 決済デモ</a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to current_user.email, settings_path %></li>
              <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <%= link_to 'サインアップ', new_user_registration_path %>
              <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
          </ul>
        </div><!-- /.container-fluid -->
      </nav>
      
      <div class="row">
        <div class="col-md-10">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/settings/index.html.erb
<h2>クレジットカードを登録する</h2>
<%= form_for settings_path, method: 'post', html: {id: 'nonce-form'} do |f| %>
  <div class="form-group">
    <label for="inputCardNumber">カード番号</label>
    <div id="sq-card-number"></div>
  </div>
  <div class="form-group">
    <label for="inputCVV">CVV/セキュリティコード</label>
    <div id="sq-cvv"></div>
  </div>
  <div class="form-group">
    <label for="inputExpirationDate">有効期限</label>
    <div id="sq-expiration-date"></div>
  </div>
  <div class="form-group">
    <label for="inputPostalCode">郵便番号</label>
    <div id="sq-postal-code"></div>
  </div>
  <button id="sq-creditcard" class="button-credit-card btn btn-default">
    カードを登録する
  </button>
  <input type="hidden" id="card_brand" name="card_brand">
  <input type="hidden" id="exp_month" name="exp_month">
  <input type="hidden" id="exp_year" name="exp_year">
  <input type="hidden" id="last_4" name="last_4">
  <input type="hidden" id="card-nonce" name="nonce">
<% end %>

<h2>登録済みカード</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <td>ブランド</td>
      <td>有効期限</td>
      <td>下4桁</td>
    </tr>
  </thead>
<% @cards.each do |card|%>
  <tr>
    <td><%= card.brand %></td>
    <td><%= card.exp_year %>年<%= card.exp_month %>月</td>
    <td><%= card.last4 %></td>
    <td><%= link_to "削除", setting_path(card.id), method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/settings/show.html.erb
<h1>Settings#show</h1>
<p>Find me in app/views/settings/show.html.erb</p>